services:
  postgres-db:
    container_name: madmotor-postgres
    image: postgres:12.2-alpine
    restart: no
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database/madmotor.sql:/docker-entrypoint-initdb.d/madmotor.sql
    networks:
      - madmotor-network
  mongo-db:
    container_name: madmotor-mongo
    image: mongo:latest
    restart: no
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/madmotor.js:/docker-entrypoint-initdb.d/madmotor.js:ro
    networks:
      - madmotor-network

  madmotor-api-nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: madmotor-api-nest
    restart: no
    env_file: .env.prod
    ports:
      - ${API_PORT}:3000
    volumes:
      - ./uploads:/app/uploads
      - ./cert:/app/cert
    networks:
      - madmotor-network
    depends_on:
      - postgres-db
      - mongo-db
networks:
  madmotor-network:
    driver: bridge